name: Update Playlist URLs

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update playlist URLs
        env:
          PLAY_URLS: ${{ secrets.PLAY_URLS }}
        run: |
          # Inhaltsaktualisierung vorbereiten
          new_content="Neuer Inhalt"

          # GitHub API verwenden, um Datei zu aktualisieren
          curl -X PUT \
            -H "Authorization: token $PLAY_URLS" \
            -H "Content-Type: application/json" \
            -d "{\"message\": \"Update playlist URLs\", \"content\": \"$(echo -n $new_content | base64)\"}" \
            "https://api.github.com/repos/tonis1000/Tonis/contents/playlist-urls.txt"
