# workflows/main.yml
name: Update Playlist URLs

on:
  push:
    paths:
      - 'urls.txt'

jobs:
  update-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print updated URLs
        run: |
          cat urls.txt
