name: Update URLs

on:
  push:
    branches:
      - main

jobs:
  update-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update URLs file
      run: |
        if [ -f urls.txt ]; then
          echo "URLs file exists"
        else
          touch urls.txt
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add urls.txt
        git commit -m "Update URLs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
